apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: land-api
  name: land-api
  namespace: default
spec:
  selector:
    matchLabels:
      app: 
  replicas: 1
  template:
    metadata:
      labels:
        app: land-api
    spec:
      containers:
      - image: us.gcr.io/teak-bebop-123023/land-api:latest
        name: land-api
        ports:
        - containerPort: 9000
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: land-api
  namespace: default
  labels:
    service: land-api
spec:
  ports:
  - port: 9000
    protocol: TCP
  selector:
    app: land-api